### ISSUE TITLE
Feature request: sumdir: Support for BLAKE2b

### ISSUE THREAD

**Issue by baltakatei** [monking/shell-utilities#1]
The default hash algorithm used by `sumdir` is SHA2's SHA256 (via `sha256sum` or `shasum -a 256`). Another algorithm I've seen as an improvement on SHA256 is [BLAKE2b](https://en.wikipedia.org/wiki/BLAKE_(hash_function)#BLAKE2) (via `b2sum` in [GNU Coreutils](https://www.gnu.org/software/coreutils/manual/html_node/b2sum-invocation.html)) which has higher throughput than `sha256sum`. Adding an option to hash using BLAKE2b (possibly via an environment variable?) could improve the performance of this script when applied to directories containing large files.

Overall, nice script. 👍

https://github.com/monking/shell-utilities/blob/a7b04331f3ba9ba71c7fa6839566423355ace93a/sumdir#L37

**Comment by monking** [comment]
Great idea! I've added an option `-a CMD` to choose either SHA256 or BLAKE2b.
I've also added a `--length N` option, which is passed through to `b2sum`, also configurable by `SUMDIR_LIST_B2_OPTS` environment variable (see `sumdir -h` or [README](https://github.com/monking/shell-utilities/blob/main/README.md#sumdir)).

[Here's the diff showing the implementation](https://github.com/monking/shell-utilities/compare/a7b0433..a006aff).

This still assumes a similarity in the interface for these commands `sha*sum` and `b2sum` (primarily that they both take the `-c FILE` option to check digests. **LATER**, I may want to make `sumdir` even more generic/future-proof by letting it only create the filename and header comment, and receive the digest content from STDIN, allowing use with *any* hashing algorithm.
